# -*- coding: utf-8 -*-
"""Geo170K.ipynb

Automatically generated by Colab.
"""

import pandas as pd

df1 =  pd.read_parquet('alignment-00000-of-00001-dad80c35097ea8fb.parquet', engine='pyarrow')
df1.tail(100)

df2 =  pd.read_parquet('qa_tuning-00000-of-00001-32a379a503a63173.parquet', engine='pyarrow')
df2.head(100)

mapping = {}
for i, row in df1.iterrows():
  mapping[row['image']] = row['conversations']

mapping2 = {}
for i, row in df2.iterrows():
  mapping2[row['image']] = row['conversations']

len(mapping.keys()), len(mapping2.keys())
final_mapping = {}
for key in mapping:
  if key in mapping2 and "geoqa_plus" in key:
    final_mapping[key] = [mapping[key], mapping2[key]]
len(final_mapping)

print("Caption: ", final_mapping['geoqa_plus/11118.png'][0][1]['value'])
print("Prompt: ", final_mapping['geoqa_plus/11118.png'][1][0]['value'].split("\n")[1])
print("Question: ", final_mapping['geoqa_plus/11118.png'][1][0]['value'].split("\n")[2])
print("Answer: ", final_mapping['geoqa_plus/11118.png'][1][1]['value'].split("\n")[1])

data = {
    'caption': [],
    'question': [],
    'answer': [],
    'image': []
}
ignored = 0
for key in final_mapping:
  try:
    caption = final_mapping[key][0][1]['value']
    question = final_mapping[key][1][0]['value'].split("\n")[2][10:]
    answer = final_mapping[key][1][1]['value'].split("\n")[1].strip()[-1]

    data['caption'].append(caption)
    data['question'].append(question)
    data['answer'].append(answer)
    data['image'].append(key)
  except:
    ignored += 1
    continue

len(data['caption']), ignored

len(data['caption'])
lengths = [len(ans.strip()) for ans in data['answer']]
set(lengths)

pd.DataFrame(data).to_csv('prepared_data.csv', index=False)
